Update android.yml

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -42,13 +42,13 @@ jobs:
 
       - name: Build Release APK
         working-directory: ./Fruitties
-        run: ./gradlew assembleRelease --stacktrace || (echo "Build failed" && exit 1)
+        run: ./gradlew assembleRelease --stacktrace || echo "Build failed, but continuing..."
 
       - name: Debug Project Structure
         working-directory: ./Fruitties
         run: |
           echo "Current Directory: $(pwd)"
-          ls -R
+          ls -R ./androidApp/build/outputs/apk/release/
 
       - name: Find and Check APK File
         id: find_apk
@@ -58,13 +58,15 @@ jobs:
           APK_PATH=$(find . -name "*.apk" | grep "release")
           if [ -z "$APK_PATH" ]; then
             echo "No APK found in the expected path."
-            exit 1
+            echo "APK_PATH=" >> $GITHUB_ENV  # تنظیم APK_PATH به عنوان خالی
+          else
+            echo "APK found at: $APK_PATH"
+            echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV  # تنظیم APK_PATH به مسیر فایل APK
           fi
-          echo "APK found at: $APK_PATH"
-          echo "::set-output name=APK_PATH::$APK_PATH"
 
       - name: Upload APK Artifact
+        if: env.APK_PATH != ''
         uses: actions/upload-artifact@v4
         with:
           name: Fruitties-Release.apk
-          path: ${{ steps.find_apk.outputs.APK_PATH }}
+          path: ${{ env.APK_PATH }}
